[greeter]
clock-format = %a %d %B %Y, %H:%M:%S
position = 30%,center 70%,center
font-name = Roboto 12
theme-name = Artix-dark
icon-theme-name = Adwaita
xft-antialias = true
#xft-dpi = 115
xft-rgba = rgb
xft-hintstyle = hintfull
background = /usr/share/backgrounds/Artix_dna_spiral_dark_bw.jpg
user-background = false
default-user-image = /usr/share/icons/artix/logo.svg
round-user-image = false
