# Z Linux foot — tema Z (paleta del splash: negro + verdes salvia)
[main]
font=monospace:size=10

[colors]
background=0b0e0c
foreground=bccbbc

# normal
regular0=1a201c
regular1=a66a6a
regular2=6fa287
regular3=c2b280
regular4=7fa3b8
regular5=b08bb5
regular6=7fb5a8
regular7=bccbbc

# bright
bright0=4a554e
bright1=d18a8a
bright2=8fd0ab
bright3=e0cf96
bright4=9fc3d8
bright5=d0aed8
bright6=93d3c0
bright7=e6f0e6

selection-foreground=0b0e0c
selection-background=6fa287
cursor=8fd0ab
