vm.swappiness=100
vm.page-cluster=0
vm.vfs_cache_pressure=50
kernel.nmi_watchdog=0
net.core.netdev_max_backlog=2500
vm.dirty_ratio=10
vm.dirty_background_ratio=5
kernel.sched_migration_cost_ns=5000000
kernel.sched_bore=1
kernel.sched_burst_inherit_type=2
kernel.sched_burst_penalty_offset=24
kernel.sched_burst_cache_lifetime=75000000
